### ISSUE TITLE
P1902R1: __cpp_lib_unwrap_ref should probably be defined in <functional>, not in <type_traits>

### ISSUE THREAD

**Issue by cpplearner** [BRevzin/sd6#1]
(Concerning p1902r1)

Since `unwrap_reference` and `unwrap_ref_decay` are defined in `<functional>` ([\[functional.syn\]](https://wg21.link/functional.syn)), their feature test macro should also be defined there.

(`unwrap_reference` and `unwrap_ref_decay` depend on `reference_wrapper`, so it makes sense for them to live in `<functional>`.)

**Comment by BRevzin** [comment]
Yep, requesting a new LWG issue for this. Either we need to move the macro into `<functional>` or move the traits into `<type_traits>`.

**Comment by BRevzin** [comment]
This is [LWG3348](https://cplusplus.github.io/LWG/issue3348).
