### ISSUE TITLE
P1902R1: __cpp_lib_constexpr_complex is missing in Wording

### ISSUE THREAD

**Issue by cpplearner** [BRevzin/sd6#2]
P1902R1 mentions:

> [P0415R1] (Constexpr for std::complex): this paper proposes to introduce the macro `__cpp_lib_constexpr_complex`. That is, introducing a new macro for this header.

But `__cpp_lib_constexpr_complex` isn't listed in the 'Wording' section, and thus is not added to the draft standard when applying P1902R1.

**Comment by BRevzin** [comment]
Oops. STL is opening an LWG issue for this one.

**Comment by BRevzin** [comment]
This is [LWG3349](https://cplusplus.github.io/LWG/issue3349) but I went ahead and applied this as part of  ca0ccc1 anyway since I think the resolution there is clear.
