### ISSUE TITLE
`<coroutine>` has no macro

### ISSUE THREAD

**Issue by bitweeder** [BRevzin/sd6#7]
While the language-level support for C++ coroutines has an assigned macro (`__cpp_coroutines`), there is no corresponding macro for library-level support. Other features split between language and library features _do_ have both sets of macros (cf. `<concepts>`). Note that simply testing `__has_include (<coroutine>)` is not in keeping with the idea of versioning feature support.

The obvious fix is to create a new macro, `__cpp_lib_coroutines`, and assign it a value of `201902L`, in keeping with the language macro.

**Comment by BRevzin** [comment]
This is [LWG 3393](https://wg21.link/lwg3393) and was adopted in Prague.
